import { defineCollection } from "vuepress-theme-plume";

export default defineCollection({
	dir: "integral",
	sidebar: [
		{
			text: "数学分析",
			collapsed: false,
			link: "/integral/",	
			items: [
				"integral-0",
				"integral-1",
				"integral-2",
				"integral-3",
				"integral-4",
				"integral-5",
				"integral-6",
				"integral-7",
				"integral-8",
				"integral-9",
				"integral-10",
				"integral-11",
				"integral-12",
				"integral-13",
				"integral-14",
				"integral-15",
				"integral-16",
				"integral-17",
				"integral-18",
				"integral-19",
				"integral-20",
				"integral-21",
				"integral-22",
				"integral-23",
				"integral-24",
				"integral-25",
				"integral-26",
				"integral-27",
				"integral-28",
				"integral-29",
				"integral-30",
				"integral-31",
				"integral-32",
				"integral-33",
				"integral-34",
				"integral-35",
				"integral-36",
				"integral-37",
				"integral-38",
				"integral-39",
				"integral-40",
				"integral-41",
				"integral-42",
				"integral-43",
				"integral-44",
				"integral-45",
				"integral-46",
			],
		},
	],
	type: "doc",
	title: "数学分析"
});