name: "IndexNow"
on:
  push:
    branches:
      # when git push to the main branch
      - main
  schedule:
    # scheduled in UTC.
    - cron:  '0 2 * * *'

jobs:
  check-and-submit:
    runs-on: ubuntu-latest
    env:
      INDEXNOW_KEY: ${{ secrets.INDEXNOW_KEY }}
      INDEXNOW_KEY_LOCATION: ${{ secrets.INDEXNOW_KEY_LOCATION }}
    steps:
      - name: submit-to-bing
        if: ${{ env.INDEXNOW_KEY != '' }}
        uses: bojieyang/indexnow-action@v1
        with:
          sitemap-location: "https://soda-official.top/sitemap.xml"  # change it
          endpoint: "www.bing.com"
          since: 1
          # minute, hour, day, week, month, year
          since-unit: "day"
          limit: 100
          key: ${{ env.INDEXNOW_KEY }}
          key-location: ${{ env.INDEXNOW_KEY_LOCATION }}
